buildscript {
    //ext.kotlin_version = '1.8.10' // You can update to 1.9.x if needed
    ext.kotlin_version = '1.9.20'


    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.1'
        //classpath 'com.android.tools.build:gradle:8.3.0'
        //classpath 'com.android.tools.build:gradle:8.1.2'
        //classpath 'com.android.tools.build:gradle:7.4.2'

        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.10"
        // NOTE: Do not place your application dependencies here; they belong in the app-level build.gradle
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
