// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfF0p3iU6osn5j9iU1UUGIm4X-KDIr0E0',
    appId: '1:913879256063:web:dc83b6474a30363e7635ca',
    messagingSenderId: '913879256063',
    projectId: 'chatify-bc1c2',
    authDomain: 'chatify-bc1c2.firebaseapp.com',
    storageBucket: 'chatify-bc1c2.appspot.com',
    measurementId: 'G-V0QZZ99WNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjVFlAf7A1LW_D4aMZL5kZ0H8k-6HbbKs',
    appId: '1:913879256063:android:9f9d6722e43f299e7635ca',
    messagingSenderId: '913879256063',
    projectId: 'chatify-bc1c2',
    storageBucket: 'chatify-bc1c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_FhoMdk6jQUgbBVp8pYdr1SDH1Z8eiZI',
    appId: '1:913879256063:ios:baa8582887b208947635ca',
    messagingSenderId: '913879256063',
    projectId: 'chatify-bc1c2',
    storageBucket: 'chatify-bc1c2.appspot.com',
    iosBundleId: 'com.example.realtimeChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_FhoMdk6jQUgbBVp8pYdr1SDH1Z8eiZI',
    appId: '1:913879256063:ios:baa8582887b208947635ca',
    messagingSenderId: '913879256063',
    projectId: 'chatify-bc1c2',
    storageBucket: 'chatify-bc1c2.appspot.com',
    iosBundleId: 'com.example.realtimeChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfF0p3iU6osn5j9iU1UUGIm4X-KDIr0E0',
    appId: '1:913879256063:web:7532d9a8160ddc9b7635ca',
    messagingSenderId: '913879256063',
    projectId: 'chatify-bc1c2',
    authDomain: 'chatify-bc1c2.firebaseapp.com',
    storageBucket: 'chatify-bc1c2.appspot.com',
    measurementId: 'G-KBSP42MEJM',
  );
}
